/**
 * `message.extra.cairn` at STORE_VERSION 4, written out by hand (CLAUDE.md §8.32).
 *
 * A literal, never generated by the writers: when the stored shape changes this file
 * stays behind as the old shape. v4 adds `index` beside `scene`, `state` and `canon`
 * (docs/decisions.md D-0070).
 *
 * **The text is v3's, deliberately.** Keeping the same four messages and the same
 * summaries makes the difference between the two fixtures exactly the one new key, which
 * is what a migration test wants to see. The envelopes follow store-v1.js through
 * store-v3.js, whose shapes were read off the corpus.
 *
 * The **record's own shape is invented here** (CLAUDE.md §3.13): no run has written one
 * yet. What was confirmed against the real chats is only that a summary is ~3 sentences
 * and names 4 to 5 people and places, measured by length and count alone — so four
 * name slots and a 100-character clause are the right order of size. Stage 0's labelling
 * pass is what confirms the rest (docs/p5-plan.md §5).
 *
 * An index record is hashed against **the summary it was derived from**, not against
 * `mes`: a resummarise has to invalidate it, and a hash of the message would not.
 */
export const STORE_V4_U0_MES = 'Wren asked whether Aster had known her brother, back before the flood took him, or whether the name only meant the same thing to her that it meant to everyone else on the harbour.';

export const STORE_V4_CANON_MES = 'Aster was quiet for a while. She had known him, she said — he had crewed the winter run with her the year before the flood, and he had been better at it than she ever was. She said she would get Wren across the water before the feast day, whatever the harbourmaster decided about the ferry.';

export const STORE_V4_U2_MES = 'Wren turned the promise over and asked what she meant to do about it, given the board still read DELAYED and the fog had not lifted all afternoon.';

export const STORE_V4_MES = 'Aster nodded at the far end of the sea wall, where a small green boat sat low against the stones, and said it was not the ferry but it had crossed worse water than this. She pulled her oilskin closed and told Wren to be ready at first light.';

const SCENE_1_TEXT = 'Aster admitted she had crewed with Wren\'s brother, and promised to get Wren across before the feast day.';
const SCENE_3_TEXT = 'Aster showed Wren a small green boat on the sea wall and said to be ready at first light.';

/** The store on message 1: a scene, its index record, and the canon batch covering 0 and 1. */
export const STORE_V4_CANON = Object.freeze({
    v: 4,
    scene: Object.freeze({
        text: SCENE_1_TEXT,
        // ST's getStringHash of STORE_V4_CANON_MES (public/scripts/utils.js:522), computed by hand.
        hash: 'h:06d80238e50fe4',
        prompt: 'h:1c2a6e3b7f0d44',
        at: '2026-09-17T09:12:00.000Z',
    }),
    /** Every slot filled: the summary says what changed lastingly and what brought it about. */
    index: Object.freeze({
        record: Object.freeze({
            kind: 'major',
            who: Object.freeze(['Aster', 'Wren']),
            what: 'Aster admitted she had crewed with Wren\'s brother',
            changed: 'Aster knew Wren\'s brother before the flood',
            because: 'Wren asked her outright',
        }),
        // getStringHash of the scene text above, not of the message, computed by hand.
        hash: 'h:1f97f38ac1f07e',
        prompt: 'h:4c8e1d07a3b592',
        at: '2026-09-17T09:12:02.000Z',
    }),
    canon: Object.freeze({
        facts: Object.freeze([
            Object.freeze({
                text: 'Wren\'s brother drowned in the spring flood.',
                entities: Object.freeze(['Wren', 'the spring flood']),
            }),
            Object.freeze({
                text: 'Aster crewed the winter run with Wren\'s brother the year before the flood.',
                entities: Object.freeze(['Aster', 'Wren']),
            }),
            Object.freeze({
                text: 'Aster promised to get Wren across the water before the feast day.',
                entities: Object.freeze(['Aster', 'Wren', 'the feast day']),
            }),
        ]),
        covers: Object.freeze([0, 1]),
        prompt: 'h:3e91f4a0c7b218',
        at: '2026-09-17T09:12:04.000Z',
    }),
});

/** The store on message 3: a scene, its index record, and the state, as v3 wrote it. */
export const STORE_V4 = Object.freeze({
    v: 4,
    scene: Object.freeze({
        text: SCENE_3_TEXT,
        // ST's getStringHash of STORE_V4_MES, computed by hand.
        hash: 'h:090cc1832c8424',
        prompt: 'h:1c2a6e3b7f0d44',
        at: '2026-09-17T09:14:00.000Z',
    }),
    /** `because` empty, because this summary does not say why — the common case. */
    index: Object.freeze({
        record: Object.freeze({
            kind: 'major',
            who: Object.freeze(['Aster', 'Wren']),
            what: 'Aster showed Wren a boat and told her to be ready at first light',
            changed: 'Wren has a crossing at first light, by boat and not by ferry',
            because: '',
        }),
        // getStringHash of the scene text above, computed by hand.
        hash: 'h:130aaab3525669',
        prompt: 'h:4c8e1d07a3b592',
        at: '2026-09-17T09:14:02.000Z',
    }),
    state: Object.freeze({
        value: Object.freeze({
            location: 'The harbour, the far end of the sea wall',
            weather: 'Fog that has not lifted all afternoon; cold and still',
            characters: Object.freeze({
                Aster: Object.freeze({ hair: 'Pinned up', outfit: 'Oilskin coat pulled closed over a fisherman\'s jumper' }),
                Wren: Object.freeze({ hair: 'Loose, damp from the fog', outfit: 'Wool coat over a grey jumper, jeans, boots' }),
            }),
        }),
        read: 2,
        // ST's getStringHash of "Wren: <U2 mes>\nAster: <reply mes>", computed by hand.
        hash: 'h:165aca72c2eaaf',
        changed: Object.freeze(['location', 'weather']),
        prompt: 'h:2b7d0c19e4a655',
        at: '2026-09-17T09:14:05.000Z',
    }),
});

/** Two exchanges: the canon batch on the second message, the state on the last. */
export function storeV4Chat() {
    return [
        userMessage(STORE_V4_U0_MES, '2026-09-17T09:11:30.000Z', 39),
        replyMessage(STORE_V4_CANON_MES, '2026-09-17T09:12:00.000Z', 62, STORE_V4_CANON),
        userMessage(STORE_V4_U2_MES, '2026-09-17T09:13:30.000Z', 33),
        replyMessage(STORE_V4_MES, '2026-09-17T09:14:00.000Z', 55, STORE_V4),
    ];
}

function userMessage(mes, sendDate, tokens) {
    return {
        name: 'Wren',
        is_user: true,
        is_system: false,
        force_avatar: 'User Avatars/wren.png',
        send_date: sendDate,
        mes,
        extra: { isSmallSys: false, reasoning: '', token_count: tokens },
    };
}

function replyMessage(mes, sendDate, tokens, store) {
    const generation = {
        api: 'textgenerationwebui',
        model: 'synthetic-model',
        reasoning: '',
        reasoning_duration: null,
        reasoning_signature: null,
        time_to_first_token: 900,
        token_count: tokens,
    };
    const started = new Date(new Date(sendDate).getTime() - 10_000).toISOString();
    return {
        name: 'Aster',
        is_user: false,
        send_date: sendDate,
        gen_started: started,
        gen_finished: sendDate,
        mes,
        extra: { ...generation, cairn: structuredClone(store) },
        swipe_id: 0,
        swipes: [mes],
        swipe_info: [{ send_date: sendDate, gen_started: started, gen_finished: sendDate, extra: { ...generation } }],
    };
}
