/**
 * `message.extra.cairn` at STORE_VERSION 2, written out by hand (CLAUDE.md §8.32).
 *
 * A literal, never generated by the writer: when the stored shape changes this
 * file stays behind as the old shape. v2 adds `state` beside `scene`
 * (docs/p3-plan.md §1). The envelopes follow store-v1.js and the corpus: a user
 * turn with `is_system: false`, `force_avatar` and no swipes (the keys all three
 * corpus chats show), then a character reply. Content is invented.
 */
export const STORE_V2_USER_MES = 'Wren pulled her collar up against the drizzle and asked whether the harbourmaster had said anything about the last crossing, or whether they were stuck on this side of the water for the night.';

export const STORE_V2_MES = 'Aster shook her head and led the way along the sea wall to the ferry terminal. Inside, the waiting room smelled of wet wool and diesel, and the board over the ticket window read DELAYED in chalk. She dropped onto a bench and said they might as well get comfortable.';

export const STORE_V2 = Object.freeze({
    v: 2,
    scene: Object.freeze({
        text: 'Aster led Wren to the ferry terminal, where the last crossing was posted as delayed.',
        // ST's getStringHash of STORE_V2_MES, computed by hand, not by our code.
        hash: 'h:1b6001cca6e13c',
        prompt: 'h:1c2a6e3b7f0d44',
        at: '2026-09-16T12:00:00.000Z',
    }),
    state: Object.freeze({
        value: Object.freeze({
            time: 'Evening',
            location: 'The ferry terminal, waiting room',
            weather: 'Drizzle outside; damp and cold indoors',
            characters: Object.freeze({
                Aster: Object.freeze({ appearance: 'Oilskin coat, hair pinned up', mood: 'resigned' }),
                Wren: Object.freeze({ appearance: 'Wool coat, collar up', condition: 'soaked through', mood: 'impatient', intent: 'find out when the ferry runs' }),
            }),
            threads: Object.freeze(['Whether the last ferry will run tonight']),
        }),
        read: 2,
        // ST's getStringHash of "Wren: <user mes>\nAster: <reply mes>", computed by hand.
        hash: 'h:0f32bd0454b13c',
        changed: Object.freeze(['location', 'characters.mood']),
        prompt: 'h:2b7d0c19e4a655',
        at: '2026-09-16T12:00:05.000Z',
    }),
});

/** The two messages the state read, the second carrying the store. */
export function storeV2Chat() {
    const generation = {
        api: 'textgenerationwebui',
        model: 'synthetic-model',
        reasoning: '',
        reasoning_duration: null,
        reasoning_signature: null,
        time_to_first_token: 900,
        token_count: 58,
    };
    return [
        {
            name: 'Wren',
            is_user: true,
            is_system: false,
            force_avatar: 'User Avatars/wren.png',
            send_date: '2026-09-16T11:58:40.000Z',
            mes: STORE_V2_USER_MES,
            extra: { isSmallSys: false, reasoning: '', token_count: 41 },
        },
        {
            name: 'Aster',
            is_user: false,
            send_date: '2026-09-16T11:59:00.000Z',
            gen_started: '2026-09-16T11:58:50.000Z',
            gen_finished: '2026-09-16T11:59:00.000Z',
            mes: STORE_V2_MES,
            extra: { ...generation, cairn: structuredClone(STORE_V2) },
            swipe_id: 0,
            swipes: [STORE_V2_MES],
            swipe_info: [{
                send_date: '2026-09-16T11:59:00.000Z',
                gen_started: '2026-09-16T11:58:50.000Z',
                gen_finished: '2026-09-16T11:59:00.000Z',
                extra: { ...generation },
            }],
        },
    ];
}
