/**
 * `message.extra.cairn` at STORE_VERSION 1, written out by hand (CLAUDE.md §8.32).
 *
 * A literal, never generated by the writer: when the stored shape changes this
 * file stays behind as the old shape, and the migration is tested against it.
 * The envelope is a character reply as the corpus stores one: no `is_system` key,
 * ISO dates, and `swipes`/`swipe_info` beside `extra`. Content is invented.
 */
export const STORE_V1_MES = 'Aster set the kettle down and said the ferry would not run until the fog lifted, so they had the whole evening to decide whether to trust the letter.';

export const STORE_V1 = Object.freeze({
    v: 1,
    scene: Object.freeze({
        text: 'Aster told Wren the ferry was delayed by fog, leaving them the evening to decide about the letter.',
        // ST's getStringHash of STORE_V1_MES, computed by hand, not by our code.
        hash: 'h:1e3ac2d2dfac79',
        prompt: 'h:1c2a6e3b7f0d44',
        at: '2026-09-16T12:00:00.000Z',
    }),
});

export function storeV1Message() {
    const generation = {
        api: 'textgenerationwebui',
        model: 'synthetic-model',
        reasoning: '',
        reasoning_duration: null,
        reasoning_signature: null,
        time_to_first_token: 900,
        token_count: 38,
    };
    return {
        name: 'Aster',
        is_user: false,
        send_date: '2026-09-16T11:59:00.000Z',
        gen_started: '2026-09-16T11:58:50.000Z',
        gen_finished: '2026-09-16T11:59:00.000Z',
        mes: STORE_V1_MES,
        extra: { ...generation, cairn: structuredClone(STORE_V1) },
        swipe_id: 0,
        swipes: [STORE_V1_MES],
        swipe_info: [{
            send_date: '2026-09-16T11:59:00.000Z',
            gen_started: '2026-09-16T11:58:50.000Z',
            gen_finished: '2026-09-16T11:59:00.000Z',
            extra: { ...generation },
        }],
    };
}
